export const SUGGESTIONS: string[] = [
  "Help me edit my school list",
  "Build a balanced reach/target/safety list",
  "Which colleges match my stats and interests?",
  "Find schools with strong computer science",
  "Find schools with strong business programs",
  "Find schools with strong pre‑med programs",
  "Compare two colleges side by side",
  "Explain the Common App sections",
  "Walk me through the UC application",
  "What should my college resume include?",
  "Brainstorm personal statement ideas",
  "Outline my Common App essay",
  "Revise my supplemental essay",
  "How to answer “Why this college?”",
  "Turn my activity into impact‑focused bullets",
  "Craft a spike from my activities",
  "Improve my extracurricular descriptions",
  "Plan my senior year coursework",
  "Should I take AP or dual enrollment?",
  "SAT vs ACT: which should I take?",
  "Make a 6‑week SAT study plan",
  "Make a 6‑week ACT study plan",
  "Do I need test scores for test‑optional?",
  "Ask a teacher for a recommendation",
  "Provide a brag sheet for recommenders",
  "Thank‑you note template for recommenders",
  "Request an interview and prep questions",
  "Practice college interview answers",
  "FAFSA: key dates and what I’ll need",
  "CSS Profile: who requires it?",
  "Estimate my financial aid offer",
  "Find merit scholarships I qualify for",
  "Write a scholarship essay outline",
  "Explain Early Action vs Early Decision",
  "Create an application deadline calendar",
  "Should I submit an arts portfolio?",
  "How to report honors and awards",
  "What makes a strong ‘additional info’ note?",
  "Strategies for waitlist letters",
  "Appeal a financial aid decision",
  "Draft an email to an admissions rep",
  "Prepare questions for a campus tour",
  "Organize my application tracker",
  "Checklist for submitting the Common App",
  "Next steps after I submit my apps",
];


