// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otwnuvpslgfopdiovvpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90d251dnBzbGdmb3BkaW92dnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NjE2NjAsImV4cCI6MjA3MzQzNzY2MH0.7LksJo-tKOSToEi0DqnHcJVl_WmviCqqXsAHnmL0-3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});